
training_pipeline_config:
  pipeline_name: FOREST_FIRE
  artifact_dir: app_artifacts

data_ingestion_config:
  dataset_download_url: https://archive.ics.uci.edu/ml/machine-learning-databases/00547/Algerian_forest_fires_dataset_UPDATE.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 
  ingested_collection: ingested_data
  ingested_train_collection: train
  ingested_test_collection: test 

data_validation_config:
  validation_config_dir: config
  schema_file_name: schema.yaml

data_transformation_config:
  KNN_neighbors : 2
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  processed_train_collection: transformed_data_train
  processed_test_collection: transformed_data_test

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.9

  randomforest_params_config:
    bootstrap: False
    criterion: gini
    max_features: auto
    max_leaf_nodes: 2
    n_estimators: 50
    n_jobs: -1
    random_state: 42

  svc_params_config:
    C: 0.05
    kernel: linear
    probability: True
    shrinking: True




model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models
  preprocessing_export_dir: column_transformer


